version: "3.9"

services:
  redis:
    image: redis:8.0
    container_name: redis8
    ports:
      - "6379:6379"
    volumes:
      - ~/.docker_data/redis8/single:/usr/share/redis/data
    command: >
      redis-server
      --port 6379
      --appendonly yes
      --appendfsync everysec
      --aof-use-rdb-preamble yes
      --dir /usr/share/redis/data
      --protected-mode no
